php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=carts Cart
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=cart_items CartItem
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=communities Community
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=community_events CommunityEvent
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=community_event_attendees CommunityEventAttendee
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=community_members CommunityMember
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=community_roles CommunityRole
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=invoices Invoice
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=orders Order
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=order_items OrderItem
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=payments Payment
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=payment_methods PaymentMethod
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=payment_banks PaymentBank
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=payment_qris PaymentQris
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=products Product
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=product_images ProductImage
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=product_categories ProductCategory
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=product_ratings ProductRating
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=shippings Shipping
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=shippers Shipper
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=store_balances StoreBalance
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=stores Store
php artisan krlove:generate:model --namespace=App\\Models --output-path=Models --table-name=user_addresses UserAddress
